// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' ;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAryTxrX7_eHEY3fhijEnUDOL8N6iexAeQ',
    appId: '1:357874550676:web:2db6bd80d501be78a07181',
    messagingSenderId: '357874550676',
    projectId: 'gabshop-app-598a8',
    authDomain: 'gabshop-app-598a8.firebaseapp.com',
    storageBucket: 'gabshop-app-598a8.firebasestorage.app',
    measurementId: 'G-WCE0ENPGZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJxsthH2DatgYL_uvcXHUVbu833Uj-Kc',
    appId: '1:357874550676:android:a1b874df7cc63f46a07181',
    messagingSenderId: '357874550676',
    projectId: 'gabshop-app-598a8',
    storageBucket: 'gabshop-app-598a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsEjsZ-Gq-ECbRdMu-2KNZKkcEZfhLj4Q',
    appId: '1:357874550676:ios:375456ef7a3f440ca07181',
    messagingSenderId: '357874550676',
    projectId: 'gabshop-app-598a8',
    storageBucket: 'gabshop-app-598a8.firebasestorage.app',
    iosBundleId: 'com.example.ebookAppWithFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsEjsZ-Gq-ECbRdMu-2KNZKkcEZfhLj4Q',
    appId: '1:357874550676:ios:375456ef7a3f440ca07181',
    messagingSenderId: '357874550676',
    projectId: 'gabshop-app-598a8',
    storageBucket: 'gabshop-app-598a8.firebasestorage.app',
    iosBundleId: 'com.example.ebookAppWithFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAryTxrX7_eHEY3fhijEnUDOL8N6iexAeQ',
    appId: '1:357874550676:web:2ccb04419b2cb3cea07181',
    messagingSenderId: '357874550676',
    projectId: 'gabshop-app-598a8',
    authDomain: 'gabshop-app-598a8.firebaseapp.com',
    storageBucket: 'gabshop-app-598a8.firebasestorage.app',
    measurementId: 'G-PMQZZLQWTC',
  );
}
